package addition;

public enum State {
    START,
    SELECT_QUESTION,
    INSTRUCTION,
    SELECT_FLOWER,
    INPUT_NUMBER_FLOWERS,
    SELECT_ACT,
    INPUT_NUMBER_SET,
    INPUT_DATE,
    SELECT_TIME,
    INPUT_ADDRESS,
    INPUT_TELEPHONE,
    INPUT_QUESTION,
    INPUT_WRAPPER,
    REGISTRATION,
    SUBMIT,
    MADE_ORDER
}
